name: Release Hide4

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Hide4.exe
        shell: bash
        run: |
          python scripts/build_release.py
          if [ -f client/build_release/Hide4 ]; then mv client/build_release/Hide4 client/build_release/Hide4.exe; fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hide4.exe
          path: client/build_release/Hide4.exe

  publish-release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Hide4.exe
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/Hide4.exe
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


